### ISSUE TITLE
Open license

### ISSUE THREAD

**Issue by janheinrichmerker** [helgeho/HadoopWebGraph#1]
I would like to use this beautiful input format in a project that has MIT License.
Unfortunately, the GNU License is not compatible, making it impossible to use your library in the current code base. Read more about it [here](https://stackoverflow.com/a/3903472/2037482) or [here](http://www.apache.org/licenses/GPL-compatibility.html).
Could you maybe change to a more "open" license, such as the Apache License, or MIT?

**Comment by janheinrichmerker** [comment]
Even more information regarding that topic: https://choosealicense.com/
I've been through the process of checking licenses of my other open source project before, and I've had a great experience with the MIT license in general, while other licenses tended to prevent others from being able to use my open source code.

**Comment by helgeho** [comment]
Hi Heinrich, I generally prefer MIT as well and use it for most of my projects. However, there's a reason for GPL 3.0 in this projects, which is also explained in the [README](https://github.com/helgeho/HadoopWebGraph/blob/master/README.md) (see at the bottom).

> This project has been published under GPL 3.0, since this license is used by WebGraph, of which parts of the code are reused here.

**Comment by janheinrichmerker** [comment]
Oh well, that's a very good reason to also use GPL. And one thing I (personally) don't like about that license.
Anyway, there would still be the option of releasing your own code under MIT license, while mentioning the GPL for the WebGraph code
